export * from './register/register.component';
export * from './login/login.component';
export * from './annotation/annotation.component';
export * from './admin/admin.component';
export * from './home/home.component';
export * from './project/project.component';
export * from './page-not-found/page-not-found.component';
export * from './gestion-role/gestion-role.component';
export * from './mes-projet/mes-projet.component';
export * from './gestionCategories/gestionCategories.component';
export * from './gestionCorpus/gestionCorpus.component';
export * from './texte/texte.component'
export * from './projects/projects.component'
